do_train: True
evaluation_strategy: epoch
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
learning_rate: 2e-5
num_train_epochs: 60
logging_strategy: epoch
save_strategy: epoch
save_total_limit: 1
seed: 42
gradient_accumulation_steps: 8
load_best_model_at_end: True
remove_unused_columns: True
metric_for_best_model: eval_loss